Models/LessonSection.cs
using DigitalMarketing2.CustomHandlers;
using Microsoft.AspNetCore.Mvc;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace DigitalMarketing2.Models
{
    public class LessonSection
    {
        [Key]
        public int LessonSectionId { get; set; }

        [DisplayName("Lesson Section Order")]
        public int LessonSectionOrder { get; set; }

        [DisplayName("Text")]
        public string? Text { get; set; }

        [DisplayName("Image")]
        public byte[]? ImageData { get; set; }

        [DisplayName("Image Type")]
        public string? ImageType { get; set; }

        // RELATIONSHIPS
        [Required]
        [DisplayName("Lesson")]
        public int LessonId { get; set; }
        public Lesson Lesson { get; set; }

        // Only one of Text and Image can be filled at a time
        public bool IsText => !string.IsNullOrEmpty(Text);
        public bool IsImage => ImageData != null;
        public bool IsEmpty => !IsText && !IsImage;
    }

    public class LessonSectionFormModel
    {
        [HiddenInput]
        [DisplayName("Lesson Section ID")]
        public int LessonSectionId { get; set; }

        [DisplayName("Lesson Section Order")]
        [Range(1, 500)]
        public int LessonSectionOrder { get; set; }

        [DisplayName("Text")]
        public string? Text { get; set; }

        [DisplayName("Image")]
        [DataType(DataType.Upload)]
        [AllowedExtensions(new string[] { ".jpg", ".jpeg", ".png", ".gif" }, ErrorMessage = "Only image files (.jpg, .jpeg, .png, .gif) are allowed.")]
        public IFormFile? Image { get; set; }

        public bool RemoveImage { get; set; }

        [Required]
        [DisplayName("Lesson")]
        public int LessonId { get; set; }
    }

}

Controllers/LessonSectionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DigitalMarketing2.Data;
using DigitalMarketing2.Models;
using Microsoft.AspNetCore.Authorization;

namespace DigitalMarketing2.Controllers
{
    public class LessonSectionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LessonSectionsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: LessonSections
        public async Task<IActionResult> Index()
        {
            return _context.LessonSection != null ?
                View(await _context.LessonSection.Include(ls => ls.Lesson).ToListAsync()) :
                Problem("Entity set 'ApplicationDbContext.LessonSection'  is null.");

            //var lessonSections = await _context.LessonSection
            //    .Include(ls => ls.Lesson)
            //    .Where(ls => ls is TextLessonSection || ls is ImageLessonSection)
            //    .Select(ls => new LessonSectionViewModel
            //    {
            //        LessonSectionId = ls.LessonSectionId,
            //        LessonId = ls.Lesson.LessonId,
            //        LessonName = ls.Lesson.Name,
            //        LessonSectionOrder = ls.Lesson.LessonOrder,
            //        Text = ls is TextLessonSection ? ((TextLessonSection)ls).Text : "N/A",
            //        Image = ls is ImageLessonSection ? ((ImageLessonSection)ls).Image : null,
            //    }).ToListAsync();

            //return View(lessonSections);
        }

        // GET: LessonSections/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.LessonSection == null)
                return NotFound();

            var lessonSection = await _context.LessonSection
                .Include(ls => ls.Lesson)
                .FirstOrDefaultAsync(m => m.LessonSectionId == id);
            if (lessonSection == null)
                return NotFound();

            // Convert byte[] ImageData to IFormFile
            IFormFile imageFile = await ConvertImageDataToFormFile(lessonSection.ImageData);

            // Generating specific LessonSectionFormModel based on its Text / Image property
            var lessonSectionForm = new LessonSectionFormModel
            {
                LessonSectionId = lessonSection.LessonSectionId,
                LessonSectionOrder = lessonSection.LessonSectionOrder,
                Text = lessonSection.Text,
                Image = imageFile ?? null,
                LessonId = lessonSection.Lesson.LessonId
            };

            ViewBag.LessonSelectList = await _context.Lesson.ToListAsync();
            return View(lessonSectionForm);
        }

        // GET: LessonSections/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create(int? LessonId) 
        {
            if (LessonId == null) return NotFound();

            //ViewBag.LessonSelectList = _context.Lesson.ToList();

            var lessonSectionForm = new LessonSectionFormModel
            {
                LessonId = (int) LessonId
            };
            return View(lessonSectionForm); 
        }

        // POST: LessonSections/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("LessonId, LessonSectionOrder, Text, Image")] LessonSectionFormModel lessonSectionForm)
        {
            ViewBag.LessonSelectList = await _context.Lesson.ToListAsync();
            if (!ModelState.IsValid) return View(lessonSectionForm);

            // Check whether ONLY ONE of Text or Image is provided
            if (string.IsNullOrEmpty(lessonSectionForm.Text) && lessonSectionForm.Image == null)
            {
                ModelState.AddModelError(string.Empty, "Please provide either Text or Image.");
                return View(lessonSectionForm);
            }

            if (!string.IsNullOrEmpty(lessonSectionForm.Text) && lessonSectionForm.Image != null)
            {
                ModelState.AddModelError(string.Empty, "Please provide either Text or Image, not both.");
                return View(lessonSectionForm);
            }

            var lesson = await _context.Lesson.FindAsync(lessonSectionForm.LessonId);
            if (lesson == null) return NotFound();

            // Convert the IFormFile to a byte array
            byte[] imageData = null;
            if (lessonSectionForm.Image != null)
            {
                using (var stream = new MemoryStream())
                {
                    await lessonSectionForm.Image.CopyToAsync(stream);
                    imageData = stream.ToArray();
                }
            }

            // Create new Lesson Section
            var lessonSection = new LessonSection
            {
                LessonSectionOrder = lessonSectionForm.LessonSectionOrder,
                Text = lessonSectionForm.Text,
                ImageData = imageData,
                ImageType = lessonSectionForm.Image?.ContentType,
                Lesson = lesson
            };

            _context.Add(lessonSection);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Details), "Lessons", new { id = lesson.LessonId });
        }

        // GET: LessonSections/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            // Check if lesson section exists
            if (id == null || _context.LessonSection == null)
                return NotFound();

            var lessonSection = await _context.LessonSection
                .Include(ls => ls.Lesson)
                .FirstOrDefaultAsync(ls => ls.LessonSectionId == id);
            if (lessonSection == null) return NotFound();

            // Convert byte[] ImageData to IFormFile
            IFormFile imageFile = await ConvertImageDataToFormFile(lessonSection.ImageData);

            // Generating specific LessonSectionFormModel based on its Text / Image property
            var lessonSectionForm = new LessonSectionFormModel
            {
                LessonSectionId = lessonSection.LessonSectionId,
                LessonSectionOrder = lessonSection.LessonSectionOrder,
                Text = lessonSection.Text,
                Image = imageFile ?? null,
                LessonId = lessonSection.Lesson.LessonId
            };

            ViewBag.LessonSelectList = await _context.Lesson.ToListAsync();
            return View(lessonSectionForm);
        }

        // POST: LessonSections/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("LessonSectionId,LessonSectionOrder, Text, Image, LessonId, RemoveImage")] LessonSectionFormModel lessonSectionForm)
        {
            // Basic Edit Validation Check
            if (id != lessonSectionForm.LessonSectionId)
                return NotFound();

            var lessonSection = await _context.LessonSection.FindAsync(id);
            if (lessonSection == null) return NotFound();

            ViewBag.LessonSelectList = await _context.Lesson.ToListAsync();
            if (!ModelState.IsValid) return View(lessonSectionForm);

            // Check if there is Image data (Existing or replaced or manually added)
            var hasImageData = false;
            if (lessonSectionForm.Image != null || (lessonSection.ImageData != null && !lessonSectionForm.RemoveImage)) 
                hasImageData = true;

            // Check whether ONLY ONE of Text or Image is provided
            if (!string.IsNullOrEmpty(lessonSectionForm.Text) && hasImageData) // Both provided
            {
                // Convert byte[] ImageData to IFormFile
                lessonSectionForm.Image = await ConvertImageDataToFormFile(lessonSection.ImageData);
                ModelState.AddModelError(string.Empty, "Please provide either Text or Image, not both.");

                return View(lessonSectionForm);
            }
            else if (string.IsNullOrEmpty(lessonSectionForm.Text) && !hasImageData) // Both not provided
            {
                // Convert byte[] ImageData to IFormFile
                lessonSectionForm.Image = await ConvertImageDataToFormFile(lessonSection.ImageData);
                ModelState.AddModelError(string.Empty, "Please provide either Text or Image.");

                return View(lessonSectionForm);
            }

            // All validations passed, proceed with update procedures
            var lesson = await _context.Lesson.FindAsync(lessonSectionForm.LessonId);
            if (lesson == null) return NotFound();

            lessonSection.LessonSectionOrder = lessonSectionForm.LessonSectionOrder;
            lessonSection.Text = lessonSectionForm.Text;
            lessonSection.Lesson = lesson;

            // If remove image is requested, remove the image
            if (lessonSection.ImageData != null && lessonSectionForm.RemoveImage)
            {
                lessonSection.ImageData = null;
                lessonSection.ImageType = null;
            }

            // If replace image is requested, replace the image (Convert IFormFile to byte[] ImageData)
            if (lessonSectionForm.Image != null)
            {
                using (var memoryStream = new MemoryStream())

Views/LessonSections/Create.cshtml
@model DigitalMarketing2.Models.LessonSectionFormModel


<section class="lessonsection-create-page min-vh-100 m-auto py-5 pt-10vh col-white w-80">
    <div class="container pt-5">
    <div class="d-flex mt-md-5 mt-3 justify-content-center">
        <a asp-controller="Lessons" asp-action="Details" asp-route-id="@Model.LessonId">
        <svg class="back-svg flex-center" height="64px" width="32px" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 26.676 26.676" xml:space="preserve" stroke="#ffffff"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <g> <path d="M26.105,21.891c-0.229,0-0.439-0.131-0.529-0.346l0,0c-0.066-0.156-1.716-3.857-7.885-4.59 c-1.285-0.156-2.824-0.236-4.693-0.25v4.613c0,0.213-0.115,0.406-0.304,0.508c-0.188,0.098-0.413,0.084-0.588-0.033L0.254,13.815 C0.094,13.708,0,13.528,0,13.339c0-0.191,0.094-0.365,0.254-0.477l11.857-7.979c0.175-0.121,0.398-0.129,0.588-0.029 c0.19,0.102,0.303,0.295,0.303,0.502v4.293c2.578,0.336,13.674,2.33,13.674,11.674c0,0.271-0.191,0.508-0.459,0.562 C26.18,21.891,26.141,21.891,26.105,21.891z"></path> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> </g> </g></svg>
        </a>  
        <h1 class="flex-center ms-3 mb-0">Create Lesson Section</h1>
    </div>
        <hr />
        <div class="col-md-8 col-10 mx-auto">
        <form asp-action="Create" enctype="multipart/form-data">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="LessonId"/>

            <div class="form-group">
                <label asp-for="LessonSectionOrder"></label>
                <input asp-for="LessonSectionOrder" class="form-control" />
                <span asp-validation-for="LessonSectionOrder" class="text-danger"></span>
            </div>
                    <hr />
            <div class="form-group">
                <label asp-for="Text"></label>
                <textarea asp-for="Text" class="form-control"></textarea>
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
                    <hr />
            <div class="form-group">
                <label asp-for="Image"></label>
                <input asp-for="Image" type="file" accept="image/*" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
             <hr />
            <div class="form-group d-flex justify-content-center">
            <button type="submit" class="btn btn-primary px-5">Create</button>
            </div>
        </form>
        </div>
    </div>
</section>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/LessonSections/Delete.cshtml
@model DigitalMarketing2.Models.LessonSectionFormModel

@{
    ViewData["Title"] = "Delete";
}

<section class="about-page min-vh-100 m-auto py-5 pt-10vh col-white w-80">

    <div class="d-flex mt-md-5 mt-3">
        <a asp-controller="Lessons" asp-action="Details" asp-route-id="@Model.LessonId">
        <svg class="back-svg flex-center" height="64px" width="32px" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 26.676 26.676" xml:space="preserve" stroke="#ffffff"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <g> <path d="M26.105,21.891c-0.229,0-0.439-0.131-0.529-0.346l0,0c-0.066-0.156-1.716-3.857-7.885-4.59 c-1.285-0.156-2.824-0.236-4.693-0.25v4.613c0,0.213-0.115,0.406-0.304,0.508c-0.188,0.098-0.413,0.084-0.588-0.033L0.254,13.815 C0.094,13.708,0,13.528,0,13.339c0-0.191,0.094-0.365,0.254-0.477l11.857-7.979c0.175-0.121,0.398-0.129,0.588-0.029 c0.19,0.102,0.303,0.295,0.303,0.502v4.293c2.578,0.336,13.674,2.33,13.674,11.674c0,0.271-0.191,0.508-0.459,0.562 C26.18,21.891,26.141,21.891,26.105,21.891z"></path> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> </g> </g></svg>
        </a>  
        <h1 class="flex-center ms-3 mb-0">Delete Lesson Section</h1>
    </div>
    <hr />
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LessonSection</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LessonSectionId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LessonSectionId)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LessonSectionOrder)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LessonSectionOrder)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        @if (!String.IsNullOrEmpty(Model.Text))
        {
            
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Text)
            </dd>
        }
        else
        {
            <dd class="col-sm-10">N/A</dd>
        }

         <dt class="col-sm-2">
             @Html.DisplayNameFor(model => model.LessonId)
          </dt>
          <dd class="col-sm-10">
              @Html.DisplayFor(model => model.LessonId)
          </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        @if (Model.Image != null)
        {
            <div>
                <img src="@Url.Action("GetImage", "LessonSections", new { id = Model.LessonSectionId })" style="max-width: 50vw; max-height: 50vh;" />
            </div>
        }
        else
        {
            <dd class="col-sm-10">N/A</dd>
        }

        

    </dl>
        <hr />
    <form asp-action="Delete">
        <input type="hidden" asp-for="LessonSectionId" />
        <input type="submit" value="Delete" class="btn btn-danger px-5" />
    </form>
</div>
</section>

Views/LessonSections/Details.cshtml
@model DigitalMarketing2.Models.LessonSectionFormModel

@{
    ViewData["Title"] = "Details";
}

<section class="about-page min-vh-100 m-auto py-5 pt-10vh col-white w-80">
    <hr />
    <div class="d-flex mt-md-5 mt-3">
        <a asp-controller="Lessons" asp-action="Details" asp-route-id="@Model.LessonId">
        <svg class="back-svg flex-center" height="64px" width="32px" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 26.676 26.676" xml:space="preserve" stroke="#ffffff"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <g> <path d="M26.105,21.891c-0.229,0-0.439-0.131-0.529-0.346l0,0c-0.066-0.156-1.716-3.857-7.885-4.59 c-1.285-0.156-2.824-0.236-4.693-0.25v4.613c0,0.213-0.115,0.406-0.304,0.508c-0.188,0.098-0.413,0.084-0.588-0.033L0.254,13.815 C0.094,13.708,0,13.528,0,13.339c0-0.191,0.094-0.365,0.254-0.477l11.857-7.979c0.175-0.121,0.398-0.129,0.588-0.029 c0.19,0.102,0.303,0.295,0.303,0.502v4.293c2.578,0.336,13.674,2.33,13.674,11.674c0,0.271-0.191,0.508-0.459,0.562 C26.18,21.891,26.141,21.891,26.105,21.891z"></path> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> </g> </g></svg>
        </a>  
        <h1 class="flex-center ms-3 mb-0">Lesson Section Details</h1>
    </div>
    <hr />
<div>
    <h4>Lesson Section</h4>
    <hr />
    <dl class="row">

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LessonSectionId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LessonSectionId)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LessonSectionOrder)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LessonSectionOrder)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        @if (!String.IsNullOrEmpty(Model.Text))
        {
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Text)
            </dd>
        }
        else
        {
            <dd class="col-sm-10">N/A</dd>
        }

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LessonId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LessonId)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        @if (Model.Image != null)
        {
            <div>
                <img src="@Url.Action("GetImage", "LessonSections", new { id = Model.LessonSectionId })" style="max-width: 50vw; max-height: 50vh;" />
            </div>
        }
        else
        {
            <dd class="col-sm-10">N/A</dd>
        }
    </dl>
</div>
</section>

Views/LessonSections/Edit.cshtml
@model DigitalMarketing2.Models.LessonSectionFormModel

@{
    ViewData["Title"] = "Edit";
}

<section class="lesson-edit-page min-vh-100 m-auto py-5 pt-10vh col-white w-80">
    <div class="container pt-5">

    <div class="d-flex mt-md-5 mt-3 justify-content-center">
        <a asp-controller="Lessons" asp-action="Details" asp-route-id="@Model.LessonId">
        <svg class="back-svg flex-center" height="64px" width="32px" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 26.676 26.676" xml:space="preserve" stroke="#ffffff"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <g> <path d="M26.105,21.891c-0.229,0-0.439-0.131-0.529-0.346l0,0c-0.066-0.156-1.716-3.857-7.885-4.59 c-1.285-0.156-2.824-0.236-4.693-0.25v4.613c0,0.213-0.115,0.406-0.304,0.508c-0.188,0.098-0.413,0.084-0.588-0.033L0.254,13.815 C0.094,13.708,0,13.528,0,13.339c0-0.191,0.094-0.365,0.254-0.477l11.857-7.979c0.175-0.121,0.398-0.129,0.588-0.029 c0.19,0.102,0.303,0.295,0.303,0.502v4.293c2.578,0.336,13.674,2.33,13.674,11.674c0,0.271-0.191,0.508-0.459,0.562 C26.18,21.891,26.141,21.891,26.105,21.891z"></path> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> </g> </g></svg>
        </a>  
        <h1 class="flex-center ms-3 mb-0">Edit Lesson Section</h1>
    </div>

    <hr />
    <div class="row">
            <div class="col-md-8 col-10 mx-auto">
            <form asp-action="Edit" enctype="multipart/form-data">

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="LessonSectionId"/>
                <div class="form-group">
                    <label asp-for="LessonId" class="control-label"></label>
                    <select asp-for="LessonId" class="form-control" asp-items="@(new SelectList(ViewBag.LessonSelectList,"LessonId","Name"))"></select>
                    <span asp-validation-for="LessonId" class="text-danger"></span>
                </div>
                    <hr />
                <div class="form-group">
                    <label asp-for="LessonSectionOrder"></label>
                    <input asp-for="LessonSectionOrder" class="form-control" />
                    <span asp-validation-for="LessonSectionOrder" class="text-danger"></span>
                </div>
                    <hr />
                <div class="form-group">
                    <label asp-for="Text"></label>
                    <textarea asp-for="Text" class="form-control"></textarea>
                    <span asp-validation-for="Text" class="text-danger"></span>
                </div>
                    <hr />
                @if (Model.Image != null)
                {
                    <div class="form-group">
                        <label>Uploaded Image:</label>
                        <span>@Model.Image.FileName</span>
                            <div class="d-flex justify-content-center">
                            <img src="@Url.Action("GetImage", "LessonSections", new { id = Model.LessonSectionId })" style="max-width: 50vw; max-height: 50vh;" />
                        </div>
                            <hr />
                        <input class="form-check-input" type="checkbox" asp-for="RemoveImage" />
                        <label class="form-check-label" asp-for="RemoveImage">
                            Remove existing image
                        </label>
                    </div>
                        <hr />
                        <div class="form-group">
                        <label asp-for="Image">Replace Image</label>
                        <input asp-for="Image" type="file" accept="image/*" />
                        <span asp-validation-for="Image" class="text-danger"></span>
                        </div>

                        <hr />
                }
                else
                {
                        <div class="form-group">
                        <label asp-for="Image"></label>
                        <input asp-for="Image" type="file" accept="image/*" />
                        <span asp-validation-for="Image" class="text-danger"></span>
                        </div>

                        <hr />
                }
                    <div class="form-group d-flex justify-content-center">
                        <button type="submit" class="btn btn-primary px-5">Edit</button>
                    </div>
            </form>
        </div>
    </div>

    </div>
</section>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/LessonSections/Index.cshtml
@model IEnumerable<DigitalMarketing2.Models.LessonSection>

@{
    ViewData["Title"] = "Index";
}
<section class="lesson-details-page min-vh-100 m-auto py-5 pt-10vh col-white w-80">
    <hr />
<h1>Lesson Section Index</h1>
    <hr />
<p>
    <a asp-action="Create">Create New</a>
</p>
    <table class="table col-white">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Lesson.LessonId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LessonSectionOrder)
            </th>
            <th>Text</th>
            <th>Image</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Lesson.LessonId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LessonSectionOrder)
            </td>
            @if (item.IsText)
            {
                <td>
                        @Html.DisplayFor(modelItem => item.Text)
                </td>
            }
            else 
            { 
                <td>N/A</td>
            }
            
            @if (item.IsImage)
            {
                <td>
                    <img src="data:image;base64,@Convert.ToBase64String(item.ImageData)" alt="Lesson Section Image" style="max-width: 800px; max-height: 800px;" /></td>
            }
            else
            {
                <td>N/A</td>
            }
            
            <td>
                <a asp-action="Edit" asp-route-id="@item.LessonSectionId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.LessonSectionId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.LessonSectionId">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>
</section>